### ISSUE TITLE
Feature list for first release

### ISSUE THREAD

**Issue by RalfG** [compomics/psm_utils#5]
### Features

- [x] `Peptidoform`
    - [x] Mass calculation
    - [x] Atomic composition calculation
    - [x] Implement `__eq__` method (based on proforma string) (#15)
    - [x] Apply fixed modifications (#19)
- [x] `PeptideSpectrumMatch`
- [x] `PSMList`
    - [x] List indexing/slicing
    - [x] Access PSMs by id through `collection` -> `run` -> `spectrum_id` dictionary (#15)
    - [x] PSMList-wide accession of PSM properties as np.array
    - [x] Decoy pattern matching
    - [x] Q-value calculation
    - [x] Modification renaming
    - [x] Filter rank-1 PSMs
- [x] `io` (Readers/Writers)
    - [x] `__init__`:
        - [x] read_file
        - [x] write_file (#19)
        - [x] convert
    - [x] Simple, generic, lossless TSV format for PSMList (#8)
    - [x] PeptideRecord (#3)
    - [x] Percolator in / out (#7)
    - [x] X!Tandem XML (#4)
    - [x] MaxQuant msms.txt (#4)
    - [x] mzIdentML
       - [x] reader (#6)
       - [x] writer (#15)
    - [x] idXML (#9)
    - [x] MSAmanda (#14)
- [x] Command line interface:
    - [x] `convert`
- [x] psm_utils online
    - [x] statistics
    - [x] convertion

### Documentation

- [x] Readme / homepage:
    - [x] About: Add general aim, goals and non-goals
    - [x] Supported formats (with reader/writer table)
    - [x] Quickstart / demo

### Deployment

- [x] pip package
- [x] bioconda package (bioconda/bioconda-recipes#37474)

### For future releases

- [ ] Reader for PeptideShaker PSM report
- [ ] Unify usage of example PSM for writers (cfr. tsv)
- [ ] Use base classes with common code for pyteomics readers and for tab-file readers

**Comment by RalfG** [comment]
https://github.com/compomics/psm_utils/releases/tag/v0.1.0
